workflows:
  android-build:
    name: Android Build
    instance_type: mac_mini_m1
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Install Capacitor CLI
        script: npm install -g @capacitor/cli
      - name: Add Android Platform
        script: npx cap add android --force
      - name: Sync Capacitor
        script: npx cap sync android
      - name: Build APK
        script: cd android && ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
